### ISSUE TITLE
Help with vscode

### ISSUE THREAD

**Issue by juan11perez** [vmorganp/Lazytainer#19]
Good day, thank you for this component.
I'm trying to set up vscode (code-server) and I cant get it to work. These are my compose entries:

```
  lazytainer: 
    container_name: lazytainer
    image: ghcr.io/vmorganp/lazytainer:master 
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
    - 8443:8443
    env_file: secrets/.env
    labels:
    - "lazytainer.group.group1.pollRate=1"
    - "lazytainer.group.group1.inactiveTimeout=60"
    - "lazytainer.group.group1.ports=8445"
    - "lazytainer.group.group1.sleepMethod=pause"


  vscode:
    container_name: vscode
    image: lscr.io/linuxserver/code-server:latest
    restart: unless-stopped
    volumes:
    - /mnt/cache/appdata/vscode:/config
    - /mnt/cache/appdata:/config/workspace/appdata 
    - /mnt/cache/lxc:/config/workspace/lxc     
    environment:
    - PUID=99
    - PGID=100
    - TZ=Asia/Dubai
    deploy:
      resources:
        limits:
          memory: 2G
    labels:
    - "com.centurylinklabs.watchtower.enable=true"
    - "lazytainer.group=group1"
    command: --port 8443 # This is specific to linuxserver/code
    network_mode: service:lazytainer
    depends_on:
    - lazytainer
```

Any guidance is much appreciated
