### ISSUE TITLE
Custom netInterface on eth0?

### ISSUE THREAD

**Issue by rbronco21** [vmorganp/Lazytainer#23]
I'm using unraid and custom networks on eth0 to separate my dockers. Is this supported? Is unraid a special case n this instance?

```
version: "3"
services:
  lazytainer:
    container_name: lazytainer
    # to build the image yourself:
    # 1. comment 'image:...'
    # 2. uncomment 'build: .'
    # 3. instead of 'docker compose up', run 'DOCKER_BUILDKIT=1 docker-compose up --build'
    image: ghcr.io/vmorganp/lazytainer:master
    # build: .
    environment:
      - VERBOSE=true # probably set this to false unless you're debugging or doing the initial demo
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "lazytainer.group.embyTest.pollRate=1"
      - "lazytainer.group.embyTest.inactiveTimeout=10"
      - "lazytainer.group.embyTest.netInterface=eth0"
      - "lazytainer.group.embyTest.ports=80"
      - "lazytainer.group.embyTest.sleepMethod=pause" # can be either "stop" or "pause", or left blank for stop

  embyTest:
    container_name: embyTest
    image: emby/embyserver
    command: --port 80
    network_mode: service:lazytainer
    depends_on:
      - lazytainer
    labels:
      - "lazytainer.group=embyTest"
```
