### ISSUE TITLE
Frontend and some issues with healthcheck/status

### ISSUE THREAD

**Issue by webysther** [vmorganp/Lazytainer#29]
I look for a solution to reduce so many stacks I have on my self-host, now about +40 and I found this project I start to using, but I used on almost every container a healthcheck which kill the usability and my current status check service with uptime kuma, which start the container every time he hits the domain.
So I want to list a few things after start using this project as a feedback:

- healthcheck affects the network traffic:

This is before change to use the project:
```yml
version: '3.9'

services:
  it-tools:
    image: corentinth/it-tools:2023.5.14-77f2efc
    container_name: app-tools
    cpuset: '0'
    networks:
      it-tools:
    expose:
      - 80
    healthcheck:
      test: [
        "CMD", "wget", "--spider", "-q", 
        "localhost"
      ]
      interval: 60s
      retries: 5
      timeout: 10s
    restart: unless-stopped

networks:
  it-tools:
    name: it-tools
```

- status check like uptime kuma going crazy because think the project is down: maybe a solution is provide a exclusive endpoint for the port like `/lazytainer/health`
- a final consideration is about the service when the user open it (in this case my wife), show is not available and this is what she says to me, maybe a great option will be have a simple page showing that the app is open and a endpoint with status 200 from `/lazytainer/start` will the the trigger to refresh the page.

Allm these things make me think about the network traffic and I realize maybe read the access log from a nginx/apache based on host make more sense, but only a "garbage brain dump"
