### ISSUE TITLE
Memory ussage issue

### ISSUE THREAD

**Issue by Heisenberg2980** [vmorganp/Lazytainer#31]
After some time running Lazytainer the machine crashes due to no RAM memory available. After some analysis I realised Lazytainer is increasing the memory ussage overtime until it consumes all available memory. As an example, after being iddle for 10 hours it is using over 400Mb of memory:

![image](https://github.com/vmorganp/Lazytainer/assets/58039006/00a69e42-aa45-4fea-b688-7c37c3dce792)

No logs are generated.

I am running the latest version Lazytainer (v2.0.4) using docker-compose, this is the docker-compose.yaml:

```
version: "3"
services:
  lazytainer:
    container_name: lazytainer
    image: ghcr.io/vmorganp/lazytainer:master
    restart: unless-stopped
    environment:
      - VERBOSE=false # probably set this to false unless you're debugging or doing the initial demo
      - TZ=Europe/London
    ports:
      - 5800:5800
      - 4443:4443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      # Firefox
      - "lazytainer.group.firefox.pollRate=5"
      - "lazytainer.group.firefox.inactiveTimeout=300"
      - "lazytainer.group.firefox.ports=5800"
      - "lazytainer.group.firefox.sleepMethod=stop" # can be either "stop" or "pause", or left blank for stop
      - "lazytainer.group.firefox.minPacketThreshold=1"
      # Kasm
      - "lazytainer.group.kasm.pollRate=5"
      - "lazytainer.group.kasm.inactiveTimeout=300"
      - "lazytainer.group.kasm.ports=4443"
      - "lazytainer.group.kasm.sleepMethod=stop" # can be either "stop" or "pause", or left blank for stop
      - "lazytainer.group.kasm.minPacketThreshold=1"
```
