### ISSUE TITLE
exec: "--port": executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by dnburgess** [vmorganp/Lazytainer#4]
Using this docker-compose as my test/example:

```
--- 
version: "3"
services: 
  lazytainer: 
    container_name: lazytainer2
    environment: 
      - PORT=8080
      - LABEL=lazytainer
      - TIMEOUT=30
      - MINPACKETTHRESH=10
      - POLLRATE=1
      - VERBOSE=true
    image: "ghcr.io/vmorganp/lazytainer:master"
    ports: 
      - "8080:8080"
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  ytdl: 
    command: --port 8080
    container_name: youtube-dl
    depends_on: 
      - lazytainer
    environment: 
      - MY_ID=dbtech
      - MY_PW=password
    image: modenaf360/youtube-dl-nas
    labels: 
      - lazytainer.marker=lazytainer
    network_mode: "service:lazytainer"
    volumes: 
      - "/home/docker/YouTube:/downfolder"
```

I end up getting this error message:
```
Pull complete ytdl 
Pulled Container lazytainer2 
Creating Container lazytainer2 
Created Container youtube-dl 
Creating Container youtube-dl 
Created Container lazytainer2 
Starting Container lazytainer2 
Started Container youtube-dl 
Starting Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "--port": executable file not found in $PATH: unknown
```

I've tried other containers as well with similar results. Is there a reason for this and can it be fixed easily for better compatibility?
