### ISSUE TITLE
No packets being detected, but puts the container to sleep

### ISSUE THREAD

**Issue by BackedUpBooty** [vmorganp/Lazytainer#41]
I've managed to spin up lazytainer and the target container (in this case carlogger) where LT can and does pause CL after 60 seconds if inactivity. During those 60 seconds I can access CL as you'd expect, but LT doesn't detect any packets (running `VERBOSE=true`, it's showing 0 packets). This is with me clicking around different pages and accessing the GUI for the CL service. 

I'm obviously missing something here but can't figure it out. I've spun up the examples separately for `satisfactory` and `minecraft` practically verbatim (changed the volumes for those two services only) and the same kind of behaviour persists. It's not a firewall issue, the subnet is wide open for testing this, and LT does put these containers on pause/stop (whichever is specified). 

Any idea what (probably really simple thing) I could be missing?

```
services:
  ## CarLogger (lubelogger)
  carlogger:
    image: ghcr.io/hargata/lubelogger:latest
    container_name: carlogger
    restart: unless-stopped
    network_mode: service:lazytainer
    mem_limit: 4g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true    
    volumes:
      - ./carlogger/config:/App/config
      - ./carlogger/data:/App/data
      - ./carlogger/documents:/App/wwwroot/documents
      - ./carlogger/images:/App/wwwroot/images
      - ./carlogger/temp:/App/wwwroot/temp
      - ./carlogger/log:/App/log
      - ./carlogger/keys:/root/.aspnet/DataProtection-Keys
    #ports:
    #  - 9099:8080
    depends_on:
      - lazytainer
    labels:
      - "lazytainer.group=ytdl"

  lazytainer:
    container_name: lazytainer
    image: ghcr.io/vmorganp/lazytainer:master
    environment:
      - VERBOSE=true # probably set this to false unless you're debugging or doing the initial demo
    ports:
      - 9099:8080 #carlogger
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "lazytainer.group.carlogger.pollRate=1"
      - "lazytainer.group.carlogger.inactiveTimeout=60"
      - "lazytainer.grou.carlogger.minPacketThreshold=1"
      - "lazytainer.group.carlogger.ports=9099"
      - "lazytainer.group.carlogger.sleepMethod=pause" # can be either "stop" or "pause", or left blank for stop
```
