### ISSUE TITLE
Issue on machine without IPV6

### ISSUE THREAD

**Issue by charettemtb** [vmorganp/Lazytainer#66]
Hi, Thanks for your project, looking forward to using this.

I got this issue 'panic: open /proc/net/udp6: no such file or directory'.
Probably because I've no ipv6 connectivity on my server.
Is it possible to render ipv6 optionnal ?

Thanks !

**Comment by vmorganp** [comment]
Just pushed a change that I think should allow you to toggle ipv4 and ipv6

Can you try updating your compose with 

```yaml
lazytainer:
  # ... configuration omitted for brevity
  environment:
    - IPV6_DISABLED=true
```
and see if that does what you need?
