### ISSUE TITLE
Using Lazytainer behind VPN (Gluetun)

### ISSUE THREAD

**Issue by PassiveLemon** [vmorganp/Lazytainer#81]
I have a setup that requires certain containers to be behind a VPN, Gluetun in my case, and I was trying to get Lazytainer working in this situation but did not have any success.
Ex:
```yaml
services:
  gluetun:
    # Shortened for brevity
    ports:
      - 1111:1111/tcp
      - 2222:2222/tcp

  lazytainer:
    image: ghcr.io/vmorganp/lazytainer:master
    container_name: lazytainer
    restart: on-failure:10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      VERBOSE: "true"
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    labels:
      lazytainer.group.container1.ports: "1111"
      lazytainer.group.container1.sleepMethod: "stop"
      lazytainer.group.container1.pollRate: "30"
      lazytainer.group.container1.inactiveTimeout: "300"
      lazytainer.group.container2.ports: "2222"
      lazytainer.group.container2.sleepMethod: "stop"
      lazytainer.group.container2.pollRate: "30"
      lazytainer.group.container2.inactiveTimeout: "300"

  container1:
    # Shortened for brevity
    network_mode: service:lazytainer
    depends_on:
      lazytainer:
        condition: service_started
    labels:
      lazytainer.group: "container1"

  container2:
    # Shortened for brevity
    network_mode: service:lazytainer
    depends_on:
      lazytainer:
        condition: service_started
    labels:
      lazytainer.group: "container2"
```
What I noticed is that, even with verbose true, the container doesn't output anything when using the network_mode of another container. However, if I expose the ports directly on Lazytainer and remove the network_mode, then it works as expected (minus the VPN part).

Is there a way to resolve this?
